### ISSUE TITLE
Dependency net-ssh >= 3 requires ruby 2.0

### ISSUE THREAD

**Issue by mozinator** [riemann/riemann-tools#126]
There is a dependency of riemann-tools that requires net-ssh >= 3 which makes it impossible to run riemann-tools on ruby 1.9.
See: https://github.com/net-ssh/net-ssh/blob/v3.0.1/CHANGES.txt#L3

Ruby 1.9 is the default on Debian Wheezy and Raspbian which means that you have the added hassle of installing ruby >= 2 via rvm / rbenv.

My proposal is to find out why net-ssh >= 3 is required and maybe remove it, downgrade or remove it.

**Comment by jamtur01** [comment]
Pretty sure this should be fixed. Please re-open if not.
