### ISSUE TITLE
exclude iso9660 filesystems from riemann-health.

### ISSUE THREAD

**Issue by gitboy** [riemann/riemann-tools#127]
should not be raising alerts for filesystems mounted via loopback mount on iso9660 images.

**Comment by jamtur01** [comment]
@gitboy Is there a good way to detect and skip these?

**Comment by gitboy** [comment]
@jamtur01 i did this;

    (where (or (and (service #"disk .*") (not (service #"disk /media")))
               (service #"proc .*")
               (service "memory") 
               (service "load")
               (service "cpu"))

**Comment by jamtur01** [comment]
Closed by #145.

**Comment by jamtur01** [comment]
@gitboy If you could test the patch in #145 that'd be awesome. Thanks!
