### ISSUE TITLE
Build a new gem file and publish

### ISSUE THREAD

**Issue by johhil** [riemann/riemann-tools#139]
Hi,

Looks like this repository has undergone some major changes lately where a lot of code have been broken out to new gem-files. Which is a nice move!

The problem is that the new gem files still have a requirement to riemann-tools. So if you install for instance riemann-docker gem it as a dependence to riemann-tools (last version in rubygems is 0.2.7). 

Is it possible to get a new version of riemann-tools built so we get a more clean dependency matrix?

Best regards

**Comment by jamtur01** [comment]
See #140.

**Comment by johhil** [comment]
Thanks @jamtur01! The pull request looks good. I'm looking forward to test this once the gem files is released

**Comment by jamtur01** [comment]
Rreleased.
