### ISSUE TITLE
No support for TLS

### ISSUE THREAD

**Issue by sophaskins** [riemann/riemann-tools#142]
The Riemann howto page includes some brief color on securing transport with TLS (http://riemann.io/howto.html#securing-traffic-using-tls). `riemann-tools` doesn't appear to have any support for this.

The hoped-for behavior is to be able to provide `tls-key`, `tls-cert`, and `tls-ca-cert` as command-line options.

I suspect that this will take some digging in to `riemann-ruby-client` and passing the data through - does that sound right? I'm totally willing to take a stab at this :)

**Comment by aphyr** [comment]
Yeah, Sophie, I think you're right--the Ruby client needs TLS support and I don't think anyone's written that yet. Please give it a shot!
On Feb 6, 2016 10:36 AM, Sophie Haskins <notifications@github.com> wrote:The Riemann howto page includes some brief color on securing transport with TLS (http://riemann.io/howto.html#securing-traffic-using-tls). riemann-tools doesn't appear to have any support for this.

The hoped-for behavior is to be able to provide tls-key, tls-cert, and tls-ca-cert as command-line options.

I suspect that this will take some digging in to riemann-ruby-client and passing the data through - does that sound right? I'm totally willing to take a stab at this :)

**Comment by jamtur01** [comment]
See this as a start on the [TLS support for the client](https://github.com/avishai-ish-shalom/riemann-ruby-client/tree/ssl).
