### ISSUE TITLE
riemann-varnish error

### ISSUE THREAD

**Issue by sujithnss** [riemann/riemann-tools#158]
Hi

I have installed riemann tools and try to run "riemann-varnish". Im getting the following error (Im using CentOS 7)

/usr/local/share/gems/gems/riemann-tools-0.2.10/bin/riemann-varnish:16:in `block in initialize': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/share/ruby/open3.rb:217:in `popen_run'
	from /usr/share/ruby/open3.rb:99:in `popen3'
	from /usr/local/share/gems/gems/riemann-tools-0.2.10/bin/riemann-varnish:15:in `initialize'
	from /usr/local/share/gems/gems/riemann-tools-0.2.10/lib/riemann/tools.rb:9:in `new'
	from /usr/local/share/gems/gems/riemann-tools-0.2.10/lib/riemann/tools.rb:9:in `run'
	from /usr/local/share/gems/gems/riemann-tools-0.2.10/bin/riemann-varnish:54:in `<top (required)>'
	from /usr/local/bin/riemann-varnish:23:in `load'
	from /usr/local/bin/riemann-varnish:23:in `<main>'

Any help on this please...

Best Regards
Sujith P V

**Comment by jamtur01** [comment]
What version of Varnish is running? Is the varnishstat binary present?

Replying on mailing list.
