### ISSUE TITLE
riemann-elasticsearch: needs exception handling

### ISSUE THREAD

**Issue by jmcarp** [riemann/riemann-tools#166]
If `tick_indices` or `tick_search` raises an exception, `tick` never reaches arguably the most important part: checking the cluster health. This can lead to missed alerts when the cluster is unhealthy and causes other checks to fail. To fix, handle exceptions from `tick_indices` and `tick_search`, or make those methods more robust.

By the way, here's a real response that `tick_search` can receive when the cluster is unhealthy, and that causes the method to fail:

`{"_shards":{"total":19402,"successful":0,"failed":0},"_all":{"primaries":{},"total":{}},"indices":{}}`

**Comment by jamtur01** [comment]
Thanks - if you have a patch that'd be awesome!
