### ISSUE TITLE
Riemann-aws fails to use instance profile with error regarding required aws keys

### ISSUE THREAD

**Issue by cstamm13** [riemann/riemann-tools#169]
I am trying to use riemann-aws with an instance profile, but it fails with a nasty fog error saying that the aws access and secret keys are required. It looks like the PR that fixes this was merged (#157), but the change isn't available when doing a normal `gem install`
`gem install --no-ri --no-rdoc -v 0.1.2 riemann-aws`
`gem install --no-ri --no-rdoc -v 0.2.11 riemann-tools`

Is there any way to make that available?

**Comment by jamtur01** [comment]
Fixed in 0.1.3. Looks like the last release didn't get incremented.

**Comment by cstamm13** [comment]
Thank you!
