### ISSUE TITLE
riemann-net: Non-zero drop/error always mapped to warning state

### ISSUE THREAD

**Issue by sslavic** [riemann/riemann-tools#177]
## Issue

What's the issue...?
Dropped packets after being incremented will continue to be reported as warning even when there are no new packets dropped. Same for error count.

I think delta should be used instead of metric in logic determining state, report warning only when delta is > 0
https://github.com/riemann/riemann-tools/blob/master/bin/riemann-net#L82

### What's your riemann-tools version?
0.2.6 but same logic is on trunk

### What platform are you on?

Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-66-generic x86_64)

**Comment by jamtur01** [comment]
Seems reasonable - happy to take a patch on this.
