### ISSUE TITLE
Split repository

### ISSUE THREAD

**Issue by lwf** [riemann/riemann-tools#61]
The dependencies for riemann-tools are spiraling out of control, now requiring mysql libraries and libxslt1 to be installed on target systems. This is just going to keep getting worse as more and more stuff is added to the main riemann-tools repository.

I have discussed the idea of splitting this repository into multiple, per-tool repos with @aphyr before and would be willing to put effort into this again if there's an interest in going in this direction.

**Comment by jamtur01** [comment]
See #136 - would love feedback and eyes on this PR! Ping @gsandie @dgtized @fborgnia @lwf @aphyr

**Comment by jamtur01** [comment]
Next steps:

- [ ] Roll gems for programs and push.
- [ ] Move riemann-tools repo to this org.
- [ ] Update Riemann tools to reflect change (warning message?).
- [ ] Updated Riemann.io docs to reflect this.

Optional.

- [ ] Build a self-maintaining GH pages site for all the utilities.

**Comment by jamtur01** [comment]
Going to close this.
