### ISSUE TITLE
riemann-zookeeper fails silently on zookeeper 3.3.x and below

### ISSUE THREAD

**Issue by dhruvp** [riemann/riemann-tools#98]
We noticed that riemann-zookeeper requires the mntr command which only comes with zookeeper 3.4 and above. It would be awesome if it uses stat for zookeeper 3.3.x and below. Additionally we didn't realize it wasn't running because it fails silently if mntr doesn't output. @tehgeekmeister.

**Comment by tehgeekmeister** [comment]
BTW, this is not just a report, we're happy to help fix this (time permitting, we've got a few higher priority things at the moment). Just getting it here so others can find out about it if they run into the same issue until then.

**Comment by jamtur01** [comment]
@tehgeekmeister We'd love a fix if you get a chance!

**Comment by tehgeekmeister** [comment]
Very unlikely to get to this now, as I don't have this problem anymore, not
having access to a zookeeper cluster. Oh well!

**Comment by jamtur01** [comment]
Please re-open if someone can provide a fix.
