### ISSUE TITLE
make tags additive to CLI tags

### ISSUE THREAD

**Issue by peterneubauer** [riemann/riemann-tools#99]
in https://github.com/aphyr/riemann-tools/blob/master/lib/riemann/tools.rb#L58, the tags coming from something like

    report(
          :service => "test",
          :metric => 1,
          :state => "ok",
          :tags => ["test"]
      )

are ignored if there also are command line tags set. I would suggest to combine them for better handling instead of silently ignoring them?

**Comment by jamtur01** [comment]
Hi @peterneubauer Any chance you could test the attached patch and make sure it works for you? Thanks!
